version: '3.1'

x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: ${FLUENT_BIT_ADDRESS}:24224

services:
  travels-app:
    container_name: travels-app
    image: travels-app
    build:
      context: .
      dockerfile: ./drools-spring-app/Dockerfile
    restart: on-failure
    environment:
      DATABASE_DOMAIN: ${DATABASE_DOMAIN}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JAEGER_DOMAIN: ${JAEGER_DOMAIN}
      JAEGER_PORT: ${JAEGER_PORT}
    ports:
      - "8080:8080"
    logging: *fluent-bit
    depends_on:
      - travels-db
    networks:
      - services
      - monitoring

  travels-db:
    image: postgres
    container_name: travels-db
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=travels
    logging: *fluent-bit
    networks:
      - services
      - monitoring

  client-app:
    image: client-app
    container_name: client-app
    build:
      context: .
      dockerfile: ./client-app/Dockerfile
    restart: on-failure
    logging: *fluent-bit
    ports:
      - "4200:4200"
    networks:
      - services
      - monitoring

networks:
  services:
    name: services
    driver: bridge
  monitoring:
    external: true
