{
 "title": "Logging, Tracing and Custom Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "all_request_total" }
   ]
  },
  {
   "title": "HTTP GET requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "get_request_total" }
   ]
  },
  {
   "title": "HTTP POST requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "post_request_total" }
   ]
  },
  {
   "title": "Loki Logging - travel-app",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{container_name=\"/travels-app\"}"
    }
   ]
  },
  {
   "title": "Loki Logging - client-app",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{container_name=\"/client-app\"}"
    }
   ]
  },
  {
   "title": "Loki Logging - travels-db",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{container_name=\"/travels-db\"}"
    }
   ]
  },
  {
   "title": "Tracing",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    { "service": "travel_recommendation" }
   ]
  }
 ]
}